 [package]
name = "Foggy Old Ebonheart - MWSE optimization hack"
description = "Decreases the view distance in Old Ebonheart exterior cells to improve performance."
homepage = "https://www.nexusmods.com/morrowind/mods/55202"
repository = "https://github.com/paranoid-nendoroid/FoggyOldEbonheart"
authors = ["paranoid nendoroid"]
version = "1.0.0"
